# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Jan  7 19:58:41 2012
#      by: pyside-uic 0.2.11 running on PySide 1.0.9
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 552)
        MainWindow.setDocumentMode(True)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtGui.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(0, 10, 56, 15))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelTitle.setFont(font)
        self.labelTitle.setWordWrap(True)
        self.labelTitle.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelTitle.setObjectName("labelTitle")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.dockPostList = QtGui.QDockWidget(MainWindow)
        self.dockPostList.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockPostList.setObjectName("dockPostList")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboSubreddit = QtGui.QComboBox(self.dockWidgetContents)
        self.comboSubreddit.setMinimumSize(QtCore.QSize(200, 0))
        self.comboSubreddit.setMaxVisibleItems(20)
        self.comboSubreddit.setObjectName("comboSubreddit")
        self.verticalLayout.addWidget(self.comboSubreddit)
        self.listPosts = QtGui.QListWidget(self.dockWidgetContents)
        self.listPosts.setAlternatingRowColors(True)
        self.listPosts.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listPosts.setGridSize(QtCore.QSize(0, 100))
        self.listPosts.setWordWrap(False)
        self.listPosts.setObjectName("listPosts")
        self.verticalLayout.addWidget(self.listPosts)
        self.lineLogin = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineLogin.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineLogin.setObjectName("lineLogin")
        self.verticalLayout.addWidget(self.lineLogin)
        self.dockPostList.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockPostList)
        self.dockWebView = QtGui.QDockWidget(MainWindow)
        self.dockWebView.setFloating(False)
        self.dockWebView.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockWebView.setObjectName("dockWebView")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.webView = QtWebKit.QWebView(self.dockWidgetContents_4)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout_3.addWidget(self.webView)
        self.dockWebView.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWebView)
        self.dockComments = QtGui.QDockWidget(MainWindow)
        self.dockComments.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockComments.setObjectName("dockComments")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeComments = QtGui.QTreeWidget(self.dockWidgetContents_5)
        self.treeComments.setAutoFillBackground(True)
        self.treeComments.setFrameShadow(QtGui.QFrame.Plain)
        self.treeComments.setAlternatingRowColors(True)
        self.treeComments.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeComments.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeComments.setIndentation(25)
        self.treeComments.setAnimated(True)
        self.treeComments.setAllColumnsShowFocus(True)
        self.treeComments.setWordWrap(True)
        self.treeComments.setHeaderHidden(True)
        self.treeComments.setObjectName("treeComments")
        self.treeComments.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.treeComments)
        self.dockComments.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockComments)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionUpvote = QtGui.QAction(MainWindow)
        self.actionUpvote.setCheckable(True)
        self.actionUpvote.setChecked(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup/upvote.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpvote.setIcon(icon)
        self.actionUpvote.setObjectName("actionUpvote")
        self.actionDownvote = QtGui.QAction(MainWindow)
        self.actionDownvote.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup/downvote.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDownvote.setIcon(icon1)
        self.actionDownvote.setObjectName("actionDownvote")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "reddit-desk", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTitle.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.dockPostList.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Post List", None, QtGui.QApplication.UnicodeUTF8))
        self.lineLogin.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Login...", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWebView.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Link", None, QtGui.QApplication.UnicodeUTF8))
        self.dockComments.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpvote.setText(QtGui.QApplication.translate("MainWindow", "Upvote", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpvote.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownvote.setText(QtGui.QApplication.translate("MainWindow", "Downvote", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownvote.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
import res_rc
